### ISSUE TITLE
Enabling theme renders entire interface unclickable.

### ISSUE THREAD

**Issue by SquidManNuva** [Saltssaumure/xp2-discord-theme#3]
![image](https://github.com/Saltssaumure/xp2-discord-theme/assets/128169943/4e8eea58-1195-433e-b71d-7970990796f3)

**Comment by jdramirez165** [comment]
Has to be Discord's update killing things. Also how come you have Windows XP taskbar on Windows 10!?

**Comment by SquidManNuva** [comment]
> Has to be Discord's update killing things. Also how come you have Windows XP taskbar on Windows 10!?

Magic :^) (Classicshell + a ton of taskbar configuration)
